Markup forum detail page
mniberyl/forust pull request #10
Opened 2020-08-23 08:18 UTC by mniberyl

* Add QuestionCard, AnswerCard, AnswerWritingCard components
* Add text-box object style
* Change card object styles
* Rename CheckBox component to Checkbox
* Fix font colors

2020-08-23 09:05 UTC, choegyumin requested changes

2020-08-23 09:05 UTC, choegyumin commented on src/components/checkbox/checkbox.jsx
>  }
컴포넌트 개발 해야되는거니까 todo 달자

2020-08-23 09:05 UTC, choegyumin commented on src/pages/forum/list/index.jsx
>            <QuestionSummaryCard role="listitem" />
`.forum`, `.forum-list` 클래스는 안쓰이니까 삭제해줘

2020-08-23 09:05 UTC, choegyumin commented on src/pages/forum/details/index.jsx
> +          <QuestionCard role="listitem" />
`.forum`, `.forum-details` 클래스는 안쓰이니까 삭제해줘

2020-08-23 09:05 UTC, choegyumin commented on src/components/question-card/question-card.scss
> +  margin-bottom: spacing(10);
이거 카드 리스트에는 전부 이 여백이 들어갈텐데 `.card-list` 오브젝트 스타일을 만들자

2020-08-23 09:05 UTC, choegyumin commented on src/pages/forum/details/index.jsx
> +          <QuestionCard role="listitem" />
QuestionCard는 페이지당 하나만 있어야 해

2020-08-23 09:05 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +          </Link>
얘는 링크일 필요가 없어 헤딩으로 만들어줘

2020-08-23 09:05 UTC, choegyumin commented on src/pages/forum/details/index.jsx
> +        <h2 className="blind" id="forum-details-heading">Question details</h2>
여기서는 질문의 제목이 헤딩으로 쓰이는게 좋아보여

2020-08-23 09:05 UTC, choegyumin commented on src/components/comments/comments.jsx
> +}) {
댓글은 하나인데 컴포넌트명은 복수형이야

2020-08-23 09:05 UTC, choegyumin commented on src/components/comments/comments.jsx
> +      </button>
benefits은 완전 뜬금없는걸? 보통은 action이라고 많이 불러
그리고 버튼에 아무 뜻이 없어. aria-label 추가해줘

2020-08-23 09:05 UTC, choegyumin commented on src/components/post-comment/post-comment.jsx
> +  const [email, setEmail] = useState('');
댓글이 여러개인데 컴포넌트명은 단수형이야
PostComments보단 CommentList가 좋을 것 같은데 아직 댓글 쓰는 곳이 게시글 카드 밖에 없으니까 일단은 Post로 맞추자

2020-08-23 09:05 UTC, choegyumin commented on src/components/post-comment/post-comment.jsx
> +      <div className="post-comment__border" />
border보다는 separator가 명확해보여

2020-08-23 09:05 UTC, choegyumin commented on src/components/post-comment/post-comment.jsx
> +        <div className="post-comment__title">3 Comments</div>
헤딩으로 만들어줘

2020-08-23 09:05 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +        </div>
benefits은 actions로 바꿔줘

2020-08-23 09:05 UTC, choegyumin commented on src/components/post-comment/post-comment.scss
> +  }
`.post-comment__border`에 좌우 margin을 -20px씩 주면 `.post-comment__wrapper` 엘리먼트는 없어도 돼

2020-08-23 09:05 UTC, choegyumin commented on src/components/question-card/question-card.scss
> +  }
`.post-comment__border`에 좌우 margin을 -20px씩 주면 `.question-card__wrapper` 엘리먼트는 없어도 돼

2020-08-23 10:28 UTC, kwonhyunjin commented on src/components/checkbox/checkbox.jsx
>  }
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/pages/forum/list/index.jsx
>            <QuestionSummaryCard role="listitem" />
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/pages/forum/details/index.jsx
> +          <QuestionCard role="listitem" />
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/components/question-card/question-card.scss
> +  margin-bottom: spacing(10);
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/pages/forum/details/index.jsx
> +          <QuestionCard role="listitem" />
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/components/question-card/question-card.jsx
> +          </Link>
수정했어~

2020-08-23 10:28 UTC, kwonhyunjin commented on src/pages/forum/details/index.jsx
> +        <h2 className="blind" id="forum-details-heading">Question details</h2>
수정했어~

2020-08-23 10:34 UTC, kwonhyunjin commented on src/components/comments/comments.jsx
> +}) {
수정했어~

2020-08-23 10:34 UTC, kwonhyunjin commented on src/components/comments/comments.jsx
> +      </button>
수정했어~

2020-08-23 11:34 UTC, choegyumin requested changes

2020-08-23 11:34 UTC, choegyumin commented on src/components/post-comments/post-comments.jsx
> +          <textarea className="post-comments__write-text" onChange={handleChange} placeholder="Write your comment here." aria-label="Add Comment" />
이거 TextArea 컴포넌트 있어
스타일가이드 보고 만들어줘

2020-08-24 08:54 UTC, mniberyl commented on src/components/post-comment/post-comment.jsx
> +  const [email, setEmail] = useState('');
수정했어

2020-08-24 08:55 UTC, mniberyl commented on src/components/post-comment/post-comment.jsx
> +      <div className="post-comment__border" />
수정했어~

2020-08-24 09:00 UTC, mniberyl commented on src/components/post-comment/post-comment.jsx
> +        <div className="post-comment__title">3 Comments</div>
수정했어

2020-08-24 09:00 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +        </div>
수정했어

2020-08-24 09:00 UTC, mniberyl commented on src/components/post-comment/post-comment.scss
> +  }
수정했어~

2020-08-25 01:45 UTC, choegyumin requested changes
```scss
// font-color
$font-color-disabled: $gray-400;
$font-color-placeholder: $gray-500;
$font-color-tertiary: $gray-600;
$font-color-secondary: $gray-700;
$font-color-primary: $gray-900;
```

이거 만들어놓고 전혀 활용 안하고 있는데 폰트 컬러 설정할 때는 이걸로 적용해

2020-08-26 08:23 UTC, choegyumin requested changes

2020-08-26 08:23 UTC, choegyumin commented on src/components/post-comments/post-comments.jsx
> +      <h2 className="post-comments__title">3 Comments</h2>
댓글이 1개일 때는 `Comment`여야 해 todo 달아 줘

2020-08-26 08:23 UTC, choegyumin commented on src/components/text-field/text-field.scss
> -  background: #fff;
이거 파일도 지우자

2020-08-26 13:17 UTC, choegyumin requested changes

2020-08-26 13:17 UTC, choegyumin commented on src/pages/forum/detail/index.jsx
> +        <AnswerWritingCard />
AnswerCard랑 AnswerWritingCard는 PostComments처럼 목록으로 표현되는게 좋을 것 같아

2020-08-26 13:17 UTC, choegyumin requested changes
QustionCard와 AnswerCard 사이에 제목 추가했어
HTML 아웃라인은 이런 구조가 좋아 보여

```
1. Forust
    1. Main menu
    2. Lorem ipsum dolor sit amet.
        1. 2 Comments
        2. 2 Answers
            1. Hyunjin's answer
                1. 2 Comments
            2. Gyumin's answer
                1. 1 Comment
            3. Write your answer
```

2020-08-26 13:18 UTC, choegyumin commented on src/components/post-comments/post-comments.jsx
> +      <h2 className="post-comments__title">3 Comments</h2>
Answer도 마찬가지야

2020-08-27 16:55 UTC, mniberyl commented on src/components/post-comments/post-comments.jsx
> +      <h2 className="post-comments__title">3 Comments</h2>
todo 달았어

2020-08-27 16:55 UTC, mniberyl commented on src/components/text-field/text-field.scss
> -  background: #fff;
지웠어

2020-08-30 13:20 UTC, choegyumin approved these changes

2020-08-30 13:24 UTC, merged