Implement login, signup pages
mniberyl/forust pull request #13
Opened 2020-10-02 07:03 UTC by mniberyl

and
* Add react-hook-form package
* Fix compile error
* Pass `ref` prop to TextField component
* Fix FormField error style
* Implement Dropdown component and Fix usage of Popover component
* Add displayName to Button component
* Remove firebase sample page

2020-10-06 14:39 UTC, choegyumin requested changes
밸리데이션 에러 메세지를 이렇게 바꿔줘.

```
this is required
→ Enter your name
→ Enter your email address
→ Enter a password (signup)
→ Enter your password (login)

Min length is 6
→ Use 6 characters or more for a password
```

2020-10-06 14:39 UTC, choegyumin commented on src/pages/login/index.jsx
> +  };
Submit을 빠르게 여러번 누르면 여러번 실행 돼.
버튼은 비활성화시켜야 하고 이 함수에서도 조건 걸어서 차단해줘.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/signup/index.jsx
> +  };
Submit을 빠르게 여러번 누르면 여러번 실행 돼.
버튼은 비활성화시켜야 하고 이 함수에서도 조건 걸어서 차단해줘.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/signup/index.jsx
> +      }, 200);
코드만 봤을 때는 `setTimeout`이 없어도 잘 작동할 것 같은데 굳이 써야하는 이유가 있다면 주석으로 간단하게 이유를 적어주는게 좋아.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/signup/index.jsx
> +              <Button className="auth-submit" type="submit" onClick={() => clearErrors()}>Create Account</Button>
submit할 때 에러를 삭제하려는거라면 `clearErrors()`  여기 넣기 보단 `handleFormSubmit `에 넣는게 좋아 보여.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/login/index.jsx
> +const Login = () => {
컴포넌트를 화살표 함수로 바꾼 이유가 있어?
디버깅할 때 컴포넌트 이름이 나오려면 `function` 키워드로 만들거나 `displayName`을 추가해야 해.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/signup/index.jsx
> +const Signup = () => {
컴포넌트를 화살표 함수로 바꾼 이유가 있어?
디버깅할 때 컴포넌트 이름이 나오려면 `function` 키워드로 만들거나 `displayName`을 추가해야 해.

2020-10-06 14:39 UTC, choegyumin commented on src/components/dropdown/dropdown.scss
> +}
이거 드롭다운 디자인 임의로 한거니까 todo는 그대로 둬.
빨리 디자인 해서 줄게.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/login/index.jsx
> +  });
로그인에서 필드값이 변경될 때 마다 밸리데이션 에러가 나오는건 과한 듯 해.
`'onSubmit'`으로 바꾸자.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/signup/index.jsx
> +  });
입력 도중에 밸리데이트하면 무슨 문제가 있는지 바로 알 수 있어서 좋지만 로그인과 마찬가지로 과하긴 해.
필드가 몇개 없어서 괜찮긴 한데 대부분 blur, submit을 채택하는 편이니까 우리도 로그인을 제외한 모든 폼을 `'onBlur'`로 하자.

2020-10-06 14:39 UTC, choegyumin commented on src/pages/login/index.jsx
> +                    })
로그인에서 비밀번호 규칙을 알려줄 필요는 없어.
`minLength` 조건은 빼줘.

2020-10-06 14:49 UTC, choegyumin requested changes

2020-10-06 14:49 UTC, choegyumin commented on src/pages/login/index.jsx
>                </FormField>
이메일 필드니까 input type을 `email`로 쓰는게 좋지만 그럼 브라우저가 자동으로 밸리데이트하게 돼.
모바일을 고려하지 않아도 가상 키보드를 쓸 수도 있으니 inputmode를 `email`로 바꿔주는게 좋아.

https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/inputmode

2020-10-06 14:49 UTC, choegyumin commented on src/pages/signup/index.jsx
>                </FormField>
이메일 필드니까 input type을 `email`로 쓰는게 좋지만 그럼 브라우저가 자동으로 밸리데이트하게 돼.
모바일을 고려하지 않아도 가상 키보드를 쓸 수도 있으니 inputmode를 `email`로 바꿔주는게 좋아.

https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/inputmode

2020-10-12 16:00 UTC, mniberyl commented on src/pages/login/index.jsx
> +                    })
수정했어

2020-10-13 04:23 UTC, mniberyl commented on src/pages/login/index.jsx
>                </FormField>
수정했어

2020-10-13 04:30 UTC, mniberyl commented on src/pages/login/index.jsx
> +  });
웅 수정했어

2020-10-13 05:06 UTC, mniberyl commented on src/pages/signup/index.jsx
> +  });
수정했어

2020-10-13 05:37 UTC, mniberyl commented on src/components/dropdown/dropdown.scss
> +}
알겠어~

2020-10-13 05:39 UTC, mniberyl commented on src/pages/login/index.jsx
> +const Login = () => {
웅 `function` 키워드로 변경했어

2020-10-13 06:03 UTC, mniberyl commented on src/pages/signup/index.jsx
> +              <Button className="auth-submit" type="submit" onClick={() => clearErrors()}>Create Account</Button>
수정하고, `login/index.jsx` 도 대응했어

2020-10-13 06:21 UTC, mniberyl commented on src/pages/signup/index.jsx
> +      }, 200);
그러네 `setTimeout` 부분 삭제했어

2020-10-13 06:26 UTC, mniberyl commented on src/pages/login/index.jsx
> +  };
밸리데이션 에러 메세지 변경했어

2020-10-13 07:22 UTC, mniberyl commented on src/pages/signup/index.jsx
> +      }, 200);
주석 달았어

2020-10-13 11:23 UTC, mniberyl commented on src/pages/login/index.jsx
> +  };
수정했어

2020-10-13 11:23 UTC, mniberyl commented on src/pages/login/index.jsx
> +  };
밸리데이션 에러 메세지도 변경했어

2020-10-19 01:59 UTC, choegyumin requested changes

2020-10-19 01:59 UTC, choegyumin commented on src/pages/login/index.jsx
> +    setDisabled(true);
`clearErrors()`할 때 alert도 삭제해줘
signup도 마찬가지야

2020-10-19 02:00 UTC, choegyumin commented on src/pages/login/index.jsx
> +  };
에러 메시지 다시 확인해줘
안맞는 것도 있고 비밀번호 에러 메시지는 signup, login 나누었어

2020-10-19 06:57 UTC, mniberyl commented on src/pages/login/index.jsx
> +  };
수정했어

2020-10-19 06:59 UTC, mniberyl commented on src/pages/login/index.jsx
> +    setDisabled(true);
수정했어

2020-10-19 09:01 UTC, choegyumin requested changes

2020-10-19 09:01 UTC, choegyumin commented on src/components/alert/alert.jsx
> +      )}
다른건 아이콘 밖에 없는데 .alert__message 엘리먼트까지 조건문 블록 안에 넣을 필요는 없어
애초에 Icon `type` 값을 `useMemo`로 메모이제이션해서 변수에 담아 쓰면 코드가 깔끔해졌을거야

2020-10-20 05:52 UTC, mniberyl commented on src/components/alert/alert.jsx
> +      )}
수정했어~

2020-10-20 14:20 UTC, choegyumin approved these changes
LGTM

2020-10-20 14:23 UTC, merged