Implement list, detail and write pages
mniberyl/forust pull request #15
Opened 2020-11-09 04:15 UTC by mniberyl

* Add @toast-ui/react-editor package
* Add Editor component
* Add Viewer component
* Add remove-markdown package
* Add dayjs package
* Implement Edit function to detail page

2020-11-28 13:56 UTC, choegyumin requested changes

2020-11-28 13:56 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isAuthor = useMemo(() => question.authorUid === currentUser.uid, [question.authorUid, currentUser.uid]);
로그인 안하고 질문 카드를 보면 런타임 에러가 발생 해
`currentUser`가 `undefined`인 것도 대응해줘야 해
다른 곳에도 이런 오류가 있는지 확인해줘

2020-11-28 13:56 UTC, choegyumin commented on src/components/post-profile/post-profile.jsx
> +        title={askedDate}
`author` 받아오고 있는데 `aria-label`은 아직 mock이 들어가있어

2020-11-28 13:56 UTC, choegyumin commented on src/components/question-card/question-card.jsx
>            <span className="question-card__count-item">Viewed 1.5m times</span>
여기는 개발 안되어있으니 todo 달아줘

2020-11-28 13:56 UTC, choegyumin commented on src/components/question-summary-card/question-summary-card.jsx
> +        />
`aria-label`은 컴포넌트 안에서 넣어주고 있으니 여기는 빠져야 해

2020-11-29 17:05 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +  const isAuthor = useMemo(() => question.authorUid === currentUser.uid, [question.authorUid, currentUser.uid]);
수정했어

2020-11-29 17:05 UTC, mniberyl commented on src/components/question-card/question-card.jsx
>            <span className="question-card__count-item">Viewed 1.5m times</span>
todo 달았어

2020-11-29 17:05 UTC, mniberyl commented on src/components/question-summary-card/question-summary-card.jsx
> +        />
수정했어

2020-11-29 17:05 UTC, mniberyl commented on src/components/post-profile/post-profile.jsx
> +        title={askedDate}
변경했어~

2020-11-30 06:51 UTC, choegyumin commented on src/components/post-profile/post-profile.jsx
> +        title={askedDate}
`author`만 넣으면 안되지. 원래 `aria-label`에 들어갈 내용에 작성자만 바꿨어야지

2020-11-30 07:08 UTC, choegyumin requested changes

2020-11-30 07:08 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isAuthor = useMemo(() => question.authorUid === currentUser?.uid, [question.authorUid, currentUser]);
`isUser`, `isAuthor` 둘 다 해당되는 내용인데

지난번에 확인해봤을 때 `firebase.auth()`는 계속 새로운 객체를 반환했었지?
그래서 dependencies에 `currentUser`를 넣는건 memoization을 안하는 것과 같아
굳이 넣겠다면 `currentUser`가 아니라 `currentUser?.uid`를 넣는게 좋아보여

근데 `currentUser?.uid`가 업데이트 되어있는지 아닌지 확인하려면 결국 `currentUser`에서 `uid`를 찾는 탐색 과정이 필요하거든?
그리고 callback 함수 안에서 또 탐색을 하니까 업데이트되지 않았을 때는 비용이 같지만 업데이트되면 비용이 두배로 들어

그러니 이런거는 `useMemo` 안쓰는게 효율적이야

2020-11-30 07:08 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
빈 값인지 확인할 때 굳이 `===` 써서 타입 비교할 필요 없어
그냥 `currentUser?.uid == null` 이렇게 해

`undefined`, `null`을 다른 값으로 취급할 때만 지금처럼 쓰는거야

2020-11-30 07:08 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
근데 `isUser`면 로그인 했다는 뜻인데 조건은 반대로 됐네
조건 뒤집고 변수 쓰고 있는 곳 전부 확인해줘

2020-11-30 07:12 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
그리고 `isUser`, `isAuthor` 둘 다 해당되는 내용인데

지난번에 확인해봤을 때 `firebase.auth()`는 계속 새로운 객체를 반환했었지?
그래서 dependencies에 `currentUser`를 넣는건 memoization을 안하는 것과 같아
굳이 넣겠다면 `currentUser`가 아니라 `currentUser?.uid`를 넣는게 좋아보여

근데 `currentUser?.uid`가 업데이트 되어있는지 아닌지 확인하려면 결국 `currentUser`에서 `uid`를 찾는 탐색 과정이 필요하거든?
그리고 callback 함수 안에서 또 탐색을 하니까 업데이트되지 않았을 때는 비용이 같지만 업데이트되면 비용이 두배로 들어

그러니 이런거는 `useMemo` 안쓰는게 효율적이야

2020-11-30 07:13 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
그리고 `isUser`, `isAuthor` 둘 다 해당되는 내용인데

지난번에 확인해봤을 때 `firebase.auth()`는 계속 새로운 객체를 반환했었지?
그래서 dependencies에 `currentUser`를 넣는건 memoization을 안하는 것과 같아
굳이 넣겠다면 `currentUser`가 아니라 `currentUser?.uid`를 넣는게 좋아보여

근데 `currentUser?.uid`가 변경되었는지 확인하려면 결국 `currentUser`에서 `uid`를 찾는 탐색 과정이 필요하거든?
그리고 callback 함수 안에서 또 탐색을 하니까 변경되지 않았을 때는 비용이 같지만 변경되면 비용이 두배로 들어

그러니 이런거는 `useMemo` 안쓰는게 효율적이야

2020-11-30 07:20 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
그리고 `isUser`, `isAuthor` 둘 다 해당되는 내용인데

지난번에 확인해봤을 때 `firebase.auth()`는 계속 새로운 객체를 반환했었지?
그래서 `useMemo`의 dependencies에 `currentUser`를 넣는건 memoization을 안하는 것과 같아
이럴 땐 `currentUser`가 아니라 `currentUser?.uid`를 넣는게 좋아

근데 `currentUser?.uid`가 변경되었는지 확인하려면 결국 `currentUser`에서 `uid`를 찾는 탐색 과정이 필요하거든?
그리고 callback 함수 안에서 또 탐색하니까 memoization을 안한 것과 비교했을 때 변경되지 않으면 비용이 같지만 변경되면 비용이 두배로 들어
결과적으로 여기는 memoization이 비효율적인거지

그러니 이런거는 `useMemo` 안쓰는게 나아

2020-11-30 08:33 UTC, mniberyl commented on src/components/post-profile/post-profile.jsx
> +        title={askedDate}
수정했어

2020-11-30 08:52 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +  const isUser = useMemo(() => currentUser?.uid === undefined, [currentUser]);
수정했어

2020-12-02 12:55 UTC, choegyumin approved these changes
.
 (ㅇ0ㅇ)
👍 / 👍
    | \

2020-12-02 12:58 UTC, merged