Implement answer feature
mniberyl/forust pull request #17
Opened 2020-12-18 15:10 UTC by mniberyl

and 
* Fix package dependencies
* Fix .eslintrc.js format
* Add `isRenderable` function
* Add color prop to Button component
* Add Confirm component
* Add AnswerWritingForm component

2020-12-18 16:45 UTC, choegyumin requested changes

2020-12-18 16:45 UTC, choegyumin commented on src/utils/react.jsx
> +  return !!node;
함수일 때 `false`, 배열일 때 length가 0이라면 `false` 조건도 추가해줘
이 외의 객체는 대응 못할테니까 그냥 두자

2020-12-18 16:45 UTC, choegyumin commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
생각해보니 페이지 접근 권한이 없는거니까 403 에러라고 봐야겠네.
메시지는 `'You don't have permission to access this page.'`로 바꾸고, 나중에 404, 403 페이지 만들자.
alert 위에 todo 달아줘

2020-12-18 16:45 UTC, choegyumin commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
그리고 글 목록 페이지에 'Ask Question' 버튼이 이 로직을 타는데
로그인 안되어있을 때는 메시지 없이 바로 로그인 페이지로 가면 돼
여기로 오지 않고 바로 가도록 버튼의 `href` 값 바꿔줘

2020-12-18 16:45 UTC, choegyumin commented on src/components/button/button.scss
> +    }
disabled 스타일은 모든 버튼이 똑같아
다른 중복된 스타일들도 따로 분리해줘

2020-12-18 16:45 UTC, choegyumin commented on src/components/backdrop/backdrop.scss
> +  z-index: map-get($z-indexes, "floating");
floating보단 dialog가 적절해보여

2020-12-18 16:45 UTC, choegyumin commented on src/components/confirm/confirm.jsx
> +export default Object.assign(Confirm, { fn });
컴포넌트를 함수로 호출할 수 있다는 의미에서 `Confirm.fn()` 괜찮긴 한데
`Confirm.open()`이 조금 더 명시적인 것 같기도 하고..

둘 중 아무거나로 해줘

2020-12-18 16:45 UTC, choegyumin commented on src/components/confirm/confirm.jsx
> +}) {
이거 나중에 애니메이션 정의해줄게 todo 달아줘

2020-12-18 16:45 UTC, choegyumin commented on src/components/modal/modal.jsx
> +      }
지금은 애니메이션 없으니까 `setInterval`, `clearInterval`을 주석 처리 하고,
todo 내용은 뒤집자

2020-12-18 17:00 UTC, choegyumin requested changes

2020-12-18 17:00 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +};
QuestionWritingCard, AnswerWritingForm이 `props`라는 prop을 받던데 무슨 용도야?
Editor에서 spread 하던데 변함이 없는데?

2020-12-18 17:00 UTC, choegyumin commented on src/components/answer-card/answer-card.jsx
> +      )}
* `edit={edit}`은 받아서 쓰는데가 없는 것 같아
* `onUpdate` prop이 빠져서 다시 본문으로 돌아오지 못해. 부모에게서 받은 `onUpdate`랑 `setEdit(false)`를 실행하는 콜백 함수 만들어서 전달해줘
* submit button의 내용은 `answer`가 있는지에 따라 AnswerWritingForm 컴포넌트가 알아서 바꿔주는게 좋아 보여
* 수정을 취소할 수도 있어야 해. submit 버튼 왼쪽에 secondary 타입으로 `Cancel` 버튼만들고 `onUpdate`처럼 `onCancel` 실행해줘

2020-12-18 17:11 UTC, choegyumin requested changes

2020-12-18 17:11 UTC, choegyumin commented on src/components/answer-card/answer-card.jsx
> +  };
객체는 hook의 dependency로 쓰이거나 render에 영향을 주는 경우 무조건 memoization 해
전부 찾아서 바꿔줘

2020-12-21 15:11 UTC, mniberyl commented on src/utils/react.jsx
> +  return !!node;
수정했어

2020-12-21 15:11 UTC, mniberyl commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
수정하고 todo 달았어

2020-12-21 15:43 UTC, mniberyl commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
아 그리고 설명, 밸리데이션 에러 메세지에도 마침표 다 찍었어

2020-12-21 15:51 UTC, mniberyl commented on src/components/button/button.scss
> +    }
수정했어

2020-12-21 15:51 UTC, mniberyl commented on src/components/backdrop/backdrop.scss
> +  z-index: map-get($z-indexes, "floating");
수정했어

2020-12-21 15:51 UTC, mniberyl commented on src/components/confirm/confirm.jsx
> +export default Object.assign(Confirm, { fn });
Confirm.open()으로 수정했어

2020-12-21 15:51 UTC, mniberyl commented on src/components/confirm/confirm.jsx
> +}) {
@todo 달아놨어

2020-12-22 07:28 UTC, choegyumin commented on src/utils/react.jsx
> +  return !!node;
`React.Children.count`가 있다는걸 잊고 있었네..
내가 댓글 달아서 추가한 두 조건은 빼고 마지막 return을 `!!node && React.Children.count(node) > 0`으로 하자

2020-12-22 07:31 UTC, choegyumin commented on src/components/button/button.scss
> +    }
disabled 말고도 더 있어 `box-shadow`, `text-decoration`, `outline` 이런거 다 확인해줘

2020-12-22 07:53 UTC, choegyumin commented on src/utils/react.jsx
> +  return !!node;
생각해보니 React.Children API가 있었네..
`React.Children.toArray()` 써서 하자

```js
React.Children
  .toArray(node)
  .filter((item) => item === 0 || !!item)
  .length > 0;
```

2020-12-22 08:59 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +};
QuestionWritingCard, AnswerWritingForm 컴포넌트에서 `props` 삭제했어

2020-12-22 11:52 UTC, choegyumin requested changes

2020-12-22 11:52 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +  }, [checkAnswer]);
`checkAnswer`, `saveEdit` 둘 다 이름만 보고 뭐하는 변수인지 판단이 불가능해

2020-12-22 11:52 UTC, choegyumin commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
중복 제거 해줘. 제거하면서 디펜던시도 다시 확인해

2020-12-22 15:16 UTC, mniberyl commented on src/utils/react.jsx
> +  return !!node;
수정했어

2020-12-22 15:16 UTC, mniberyl commented on src/components/button/button.scss
> +    }
수정했어

2020-12-22 15:44 UTC, mniberyl commented on src/components/modal/modal.jsx
> +      }
수정했어

2020-12-22 15:45 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +};
수정했어

2020-12-22 17:03 UTC, mniberyl commented on src/components/answer-card/answer-card.jsx
> +  };
수정했고, 답변 외에 memoization 해야할 부분은 PR 따로 올릴게~

2020-12-22 17:04 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +  }, [checkAnswer]);
수정했어

2020-12-22 17:04 UTC, mniberyl commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
수정했어

2020-12-23 08:44 UTC, mniberyl commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
수정했어

2020-12-23 15:52 UTC, choegyumin commented
이거랑 관련없긴 한데 `_document.jsx`에 html 태그도 next/document의 Html 컴포넌트로 바꿔줘

2020-12-23 18:18 UTC, mniberyl commented on src/components/answer-card/answer-card.jsx
> +      )}
수정했어

2020-12-28 12:29 UTC, choegyumin commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
변수명은 그대로네

2020-12-28 12:31 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +  }, [checkAnswer]);
`hasAnswer`는 쓰는곳이 하나 밖에 없는데 메모이제이션 하지 말고 `answer != null` 하는게 좋아보여

2020-12-28 12:44 UTC, choegyumin commented on src/components/answer-card/answer-card.jsx
> +      )}
수정 취소할 때 컨펌 띄워야겠네.. 아래 처럼 해줘

---

**Are you sure?**

Are you sure you want to discard your unsaved changes?
This action cannot be reversed.

[Cancel] [Discard changes]

2020-12-28 12:46 UTC, choegyumin commented on src/components/modal/modal.jsx
> +      }
`document.body.removeChild(container);`는 살려야지

2020-12-28 12:47 UTC, choegyumin commented on src/components/button/button.scss
> +    }
주석 필요 없으면 지워줘

```scss
    &:active {
      background-color: $red-dark;
      border-color: $red-dark;
      // box-shadow: none;
      // outline: none;
    }
```

2020-12-28 12:49 UTC, choegyumin commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
버튼의 `href`를 바꿔주라는게 Button 컴포넌트에 넣으란 뜻이 아니고 그 위의 Link 컴포넌트의 `href` 말하는거야
그리고 로그인이 되어있는지 안되어있는지도 확인해야지

2020-12-28 15:01 UTC, choegyumin commented on src/components/answer-card/answer-card.jsx
> +  }, [isUser, isEdit]);
if 블럭 끝나고 페이지 이동하기전에 잠깐 수정 폼이 떠
question-card 처럼 return 하거나 else 블럭으로 감싸줘

2020-12-29 14:33 UTC, mniberyl commented on src/pages/forum/write/[[...slug]].jsx
>    }, [questionUid, router]);
수정했어

2020-12-29 14:33 UTC, mniberyl commented on src/components/button/button.scss
> +    }
수정했어

2020-12-29 14:33 UTC, mniberyl commented on src/components/modal/modal.jsx
> +      }
수정했어

2020-12-29 14:33 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +  }, [checkAnswer]);
수정했어

2020-12-29 14:33 UTC, mniberyl commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
수정했어

2020-12-29 14:33 UTC, mniberyl commented on src/components/answer-card/answer-card.jsx
> +  }, [isUser, isEdit]);
수정했어

2021-01-04 13:02 UTC, choegyumin commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
question-summary-card.jsx 도 바꿔줘

2021-01-04 13:19 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +  }, [checkAnswer]);
메모이제이션도 필요 없고 변수로 만들 필요도 없다는 뜻이였는데 변수로 만드는 건 딱히 상관없으니까 resolve 할게

2021-01-04 13:21 UTC, choegyumin requested changes
(removed)

2021-01-04 13:29 UTC, choegyumin requested changes

2021-01-04 13:29 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
>    }, [onUpdate]);
https://blog.sonim1.com/220
다 찾아서 바꿔

2021-01-04 13:29 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  }}
주석 들어갔어

2021-01-04 13:29 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
>    padding: spacing(25) spacing(20) 0 0;
`top` 값을 .app-header 만큼 주는게 좋아 보여

2021-01-04 13:52 UTC, choegyumin requested changes
비회원일 때 답변 폼이 활성화되어 있었네..

Editor의 initialValue는 `###### You must login to post answer.` 넣고,
onFocus 이벤트 발생할 때 로그인 페이지로 보내면 될 것 같아
그리고 .answer-writing-card__submit은 비활성화 해 줘

댓글도 활성화되어 있는데 이건 아직 개발 안한거니까 todo 달아놔

2021-01-05 10:09 UTC, mniberyl commented on src/components/answer-card/answer-card.jsx
> +      )}
수정했어

2021-01-05 14:42 UTC, mniberyl commented on src/components/app-nav/app-nav.scss
>    padding: spacing(25) spacing(20) 0 0;
수정했어~

2021-01-05 14:42 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  }}
지웠어~

2021-01-05 14:42 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
>    }, [onUpdate]);
수정했어

2021-01-05 14:42 UTC, mniberyl commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
수정했어

2021-01-08 14:39 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
>    padding: spacing(25) spacing(20) 0 0;
app-header의 높이를 변수에 담아서 돌려쓰자

2021-01-08 14:44 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
>    padding: spacing(25) spacing(20) 0 0;
그리고 height 이상한 값 넣지말고 `height: max-content;` 또는 `align-self: flex-start;`로 사이즈 맞추는게 좋아 보여

2021-01-08 14:46 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  }}
이번엔 다른 주석이 추가됐는데 필요없는거 다 확인하고 삭제해줘

2021-01-08 14:50 UTC, choegyumin commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
forum/list/index.js에도 비슷한게 있었네.. 이것도 수정해줘

```js
const question = snap.docs.map((doc) => ({
  id: doc.id,
  ...doc.data(),
}));
```

2021-01-08 15:10 UTC, choegyumin requested changes

2021-01-08 15:10 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  onFocus={() => { router.replace('/login'); }}
로그인 안되어있을 때 보내야지
그리고 `onChange`는 어쩔 수 없지만 `onFocus` 함수는 메모이제이션 해줘

2021-01-10 11:52 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  onFocus={() => { router.replace('/login'); }}
수정했어

2021-01-10 11:52 UTC, mniberyl commented on src/components/app-nav/app-nav.scss
>    padding: spacing(25) spacing(20) 0 0;
수정했어

2021-01-10 11:52 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +                  }}
수정했어

2021-01-10 11:53 UTC, mniberyl commented on src/pages/forum/detail/[id].jsx
> +  }, [answers]);
수정했어

2021-01-16 12:54 UTC, choegyumin requested changes

2021-01-16 12:54 UTC, choegyumin commented on src/components/answer-writing-form/answer-writing-form.jsx
> +    }
뒤로가기하면 돌아갈 수 있게 `router.push`로 바꿔줘

2021-01-16 13:53 UTC, mniberyl commented on src/components/answer-writing-form/answer-writing-form.jsx
> +    }
수정했어

2021-01-16 14:08 UTC, choegyumin approved these changes

2021-01-16 14:18 UTC, merged