Markup signup page
mniberyl/forust pull request #6
Opened 2020-07-12 11:20 UTC by mniberyl

* Add packages
* Construct stylesheets by ITCSS
* Add Button, FormField, TextField components
* Add AuthLayout component
* Add Signup page component

2020-07-12 14:49 UTC, choegyumin requested changes

2020-07-12 14:49 UTC, choegyumin commented on src/components/button/button.scss
> +  display: flex;
버튼은 인라인 요소로 만드는게 좋아 보이네요. `inline-flex`로 해주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/components/button/button.scss
> +  background: $green;
스타일 중복됐어요.

2020-07-12 14:49 UTC, choegyumin commented on src/components/button/button.scss
> +  line-height: 2.86;
line-height를 height랑 맞추려는거면 명시적으로 `40px`을 쓰는게 좋아보여요.

2020-07-12 14:49 UTC, choegyumin commented on src/components/form-field/form-field.jsx
> +    <div className="form-field">
`className`을 비롯해 다른 attribute도 입력할 수 있게 만들어주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/components/text-field/text-field.scss
> +}
`:focus` 때문에 `.text-field` 뿐만 아니라 모든 엘리먼트에 스타일이 적용돼요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.jsx
> +      <h1 className="visually-hidden">Join the community And solve problem.</h1>
section 태그는 필요없어 보이네요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.jsx
> +      <h1 className="visually-hidden">Join the community And solve problem.</h1>
h1은 문서에 하나만 사용하는 걸 권장해요.
이미 페이지에서 `<h1 className="visually-hidden">FORUST</h1>`를 선언하고 있네요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.jsx
> +      </div>
`Logo` 라는 내용은 사용자에게 불필요해요.
alt를 `Home`으로 바꿔서 메인 페이지로 이동한다는걸 알려주는게 좋아 보이네요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.jsx
> +          </p>
텍스트 확인하고 바꿔주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.scss
> +  height: 1080px;
큰 모니터에서도 height가 가득 차게 해주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/layouts/auth-layout/auth-layout.scss
> +  padding-bottom: spacing(24);
하나로 합치는게 좋아보여요.

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.jsx
> +      <Layout />
Layout을 그냥 바닥에 까는게 아니라 `children`을 받도록 개선해서 거기에 마크업하는게 낫지 않을까요?

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.jsx
> +          </div>
`Sign Up`, `Sign In`이 사용자의 잦은 실수를 유발해서 `Login`으로 한건데 뭔가 어색하네요.
`Sign Up`을 아래 버튼과 맞춰서 `Create Account`로 바꾸는게 좋을 것 같아요.

컴포넌트 명은 URL로 쓰이니 그대로 두고 `Sign up to Forust`만 `Create your Forust Account`로 바꿔주세요.
디자인에도 반영할게요.

그리고 h1은 문서에 하나만 사용하는 걸 권장하니 h2로 해주세요.
그리고 아래에 적절해보이는 헤딩(`Create your Forust Account`)이 있는데 굳이 `.visually-hidden` 클래스를 써가며 새로운 엘리먼트를 만들 필요는 없어 보여요.

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.jsx
> +              Already have an account?
디자인에 그리드 시스템이 없어서요, 전통적인 방식으로 필드에 인라인 스타일을 넣어서 width를 제어하는게 더 관리하기 쉬워 보이네요.
일단 forum 디자인이 어떻게 나올지 모르니 디자인 보고 개선하기로 해요.

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.jsx
> +              <a href="/">Sign in.</a>
`Login`으로 텍스트 바꿔주시고 링크도 미리 넣어주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.scss
> +}
AuthLayout 컴포넌트가 `children`을 받을 수 있으면 이 엘리먼트와 스타일도 레이아웃으로 옮길 수 있지 않을까요?

2020-07-12 14:49 UTC, choegyumin commented on src/styles/generic/_reset.scss
> +}
기본 `font-size`와 `line-height`도 넣으면 좋을 것 같아요.
그리고 문서 최소 width는 1200px로 해주세요.

2020-07-12 14:49 UTC, choegyumin commented on src/styles/settings/_color.scss
> +$indigo-200: #eceff2;
용도별로 영역을 나눠주세요. 빈줄과 순서 없이 섞여있으니까 헷갈리네요.

gray / indigo / chromatic / font-color

2020-07-12 14:49 UTC, choegyumin commented on src/styles/tools/_spacing.scss
> +}
몇단계의 여백인지를 표현하는거니까 `$base`보단 `$level`이 적절해보여요.

2020-07-12 14:49 UTC, choegyumin commented on src/styles/utils/_visually-hidden.scss
> +}
이거 하나만 덜렁 두고 파일명까지 통일하기는 좀 그런데..
접근성을 위한거라면 `_a11y.scss`, 화면에 보여주거나 숨기려는거면 `_display.scss`로  파일명을 바꾸어서 파일의 방향을 정하는게 좋아보여요.

2020-07-12 14:49 UTC, choegyumin commented on src/pages/signup/index.scss
> +}
width 필요 없어 보여요.

2020-07-12 14:51 UTC, choegyumin requested changes
* 이미지 파일명도 케밥 케이스로 바꿔주세요.
* BEM을 쓰고 있으니까 전부 유니크한 클래스를 만들고, 선택자를 상속받은 코드는 전부 개선해주세요.
* 폰트 스타일 중 중복되거나 불필요한 선언이 많아요. common component면 필요할 수 있지만 페이지나 레이아웃 컴포넌트의 HTML 구조는 변하지 않는데 `font-*`, `letter-spacing`, `line-height`를 매번 재선언할 필요는 없어 보이네요.

2020-07-12 15:16 UTC, choegyumin requested changes

2020-07-12 15:16 UTC, choegyumin commented on src/pages/signup/index.jsx
> +            </div>
placeholder 빼주세요. 나중에 forum에서 쓰이니 스타일은 필요하지만 여기는 불필요해요.

2020-07-12 15:24 UTC, choegyumin requested changes

2020-07-12 15:24 UTC, choegyumin commented on src/pages/signup/index.jsx
> +export default function Signup({ error }) {
`error`를 props에서 받나요??
state로 관리 되어야할 텐데 일단 마크업이니까 삭제만 하고 FormField에 넣은것도 전부 빼주세요.

2020-07-13 08:44 UTC, mniberyl commented on src/components/button/button.scss
> +  display: flex;
수정했어요.

2020-07-13 08:44 UTC, mniberyl commented on src/components/button/button.scss
> +  background: $green;
수정했어요.

2020-07-13 08:44 UTC, mniberyl commented on src/components/button/button.scss
> +  line-height: 2.86;
수정했어요.

2020-07-13 08:45 UTC, mniberyl commented on src/styles/generic/_reset.scss
> +}
수정했어요.

2020-07-13 08:48 UTC, mniberyl commented on src/styles/settings/_color.scss
> +$indigo-200: #eceff2;
수정했어요.

2020-07-13 08:48 UTC, mniberyl commented on src/styles/tools/_spacing.scss
> +}
수정했어요.

2020-07-13 08:48 UTC, mniberyl commented on src/styles/utils/_visually-hidden.scss
> +}
수정했어요.

2020-07-13 12:09 UTC, choegyumin commented on src/styles/generic/_reset.scss
> +}
브라우저 기본값과 동일한 스타일은 html에 선언할 필요가 없어요. 삭제해주세요.

2020-07-13 12:10 UTC, choegyumin commented on src/styles/settings/_color.scss
> +$indigo-200: #eceff2;
주석이 잘못 달렸어요. 그리고 gray 앞에는 띄어쓰기가 2개 들어갔어요.

2020-07-13 12:12 UTC, choegyumin commented
이 PR 까지만 존댓말 하고 그냥 반말하자~~

2020-07-13 13:53 UTC, mniberyl commented on src/styles/settings/_color.scss
> +$indigo-200: #eceff2;
네, 다시 수정했어요.

2020-07-13 13:53 UTC, mniberyl commented on src/styles/generic/_reset.scss
> +}
네, 다시 수정했어요.

2020-07-13 15:05 UTC, mniberyl commented on src/components/form-field/form-field.jsx
> +    <div className="form-field">
수정했어요.

2020-07-13 15:05 UTC, mniberyl commented on src/components/text-field/text-field.scss
> +}
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.jsx
> +      <h1 className="visually-hidden">Join the community And solve problem.</h1>
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.jsx
> +      <h1 className="visually-hidden">Join the community And solve problem.</h1>
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.jsx
> +      </div>
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.jsx
> +          </p>
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.scss
> +  height: 1080px;
수정했어요.

2020-07-13 15:52 UTC, mniberyl commented on src/layouts/auth-layout/auth-layout.scss
> +  padding-bottom: spacing(24);
수정했어요.

2020-07-13 16:57 UTC, mniberyl commented on src/pages/signup/index.jsx
> +          </div>
수정했어요.

2020-07-13 16:57 UTC, mniberyl commented on src/pages/signup/index.jsx
> +              <a href="/">Sign in.</a>
수정했어요.

2020-07-13 16:57 UTC, mniberyl commented on src/pages/signup/index.scss
> +}
수정했어요.

2020-07-13 16:58 UTC, mniberyl commented on src/pages/signup/index.jsx
> +            </div>
수정했어요.

2020-07-13 16:58 UTC, mniberyl commented on src/pages/signup/index.jsx
> +export default function Signup({ error }) {
수정했어요.

2020-07-14 06:06 UTC, choegyumin commented on src/pages/signup/index.jsx
> +              <a href="/">Sign in.</a>
url도 login으로 바꿔주세요.

2020-07-14 06:17 UTC, choegyumin requested changes

2020-07-14 06:17 UTC, choegyumin commented on src/components/form-field/form-field.jsx
> +      <p className="form-field__message">Error Message</p>
그냥 텍스트 넣지말고 `error` prop 넣어주세요. `error` prop이 없을 땐 엘리먼트 삭제해주세요.

2020-07-14 06:24 UTC, choegyumin commented
개발 끝나고 merge하기 전에 봐야할 체크리스트에요. 이거는 모여서 화면 보면서 결정해요.

* meta 태그 정의
* 인터랙션 스타일 개선. 구두로 정하고 스타일가이드에 정리할게요.
  * a 태그는 hovered, focused 상태일 때 밑줄 추가
  * 나머지는 hovered, focused 상태일 때 트랜지션 추가
    * Motion: `ease-in`, `ease-out`, `ease-in-out`
    * Speed(Duration): `fast`, `normal`, `slow`

2020-07-14 07:18 UTC, mniberyl commented on src/pages/signup/index.jsx
> +      <Layout />
수정했어요.

2020-07-14 07:18 UTC, mniberyl commented on src/pages/signup/index.jsx
> +              <a href="/">Sign in.</a>
네, 수정했어요.

2020-07-14 07:18 UTC, mniberyl commented on src/components/form-field/form-field.jsx
> +      <p className="form-field__message">Error Message</p>
수정했어요.

2020-07-15 05:42 UTC, choegyumin approved these changes
LGTM

2020-07-15 05:43 UTC, merged