Markup login page
mniberyl/forust pull request #7
Opened 2020-07-15 11:01 UTC by mniberyl

* Markup login page

2020-07-15 11:24 UTC, choegyumin requested changes

2020-07-15 11:24 UTC, choegyumin commented on src/components/checkbox/checkbox.scss
> +
이거 체크상태 스타일도 입혀야하니까 todo 달아줘
`// @todo 집에 가서 저녁 먹기` 이런식으로 달면 돼

2020-07-15 11:24 UTC, choegyumin commented on src/pages/login/index.jsx
> +              </label>
얘는 row가 아닌걸? 클래스명 다시 지어줘.
여기서만 쓸거니까 `Keep me logged in.`이랑 의미를 맞추는 것도 좋아 보여

2020-07-15 11:24 UTC, choegyumin commented on src/styles/pages/_auth.scss
> +}
BEM!!!!!!!

2020-07-15 11:24 UTC, choegyumin commented on src/styles/pages/_auth.scss
> +}
나 아직 화면을 못봤는데 이거 체크박스 표현한거지?
이거 디자인 나오면 하고 작업한 건 stash에 올려놔

2020-07-15 11:30 UTC, choegyumin requested changes
지난번에 리뷰 안했는데 접근성, 사용성 고려하면 아무래도 포커스 스타일은 없애면 안될 것 같아.
아래걸로 _reset.scss 수정해줘

```scss
*:focus {
  outline: none;
}
```

```scss
html *:focus {
  outline: initial;
  outline-style: auto;
  outline-color: $green-dark;
}

[tabindex^='-']:focus {
  outline-style: none;
}
```

이거 수정하고 포커스 상태 디자인 적용된 엘리먼트들도 대응해줘
<del>그리고 button은 box-shadow 대신 outline으로 포커스 스타일 입히면 될거야</del> outline은 border-radius가 안먹지.. 이건 무시해

2020-07-15 15:26 UTC, mniberyl commented on src/components/checkbox/checkbox.scss
> +
수정했어~

2020-07-15 15:29 UTC, mniberyl commented on src/pages/login/index.jsx
> +              </label>
수정했어~

2020-07-15 15:29 UTC, mniberyl commented on src/styles/pages/_auth.scss
> +}
고쳤어~

2020-07-15 15:30 UTC, mniberyl commented on src/styles/pages/_auth.scss
> +}
수정했어~

2020-07-16 04:48 UTC, choegyumin commented on src/pages/login/index.jsx
> +              </label>
재사용될 일이 전혀 없는 스타일이라 `keep-auth`, `keep-logged-in` 같은 이름이 좋아보여

2020-07-16 04:50 UTC, choegyumin commented on src/pages/login/index.jsx
> +              </label>
그리고 `htmlFor` 없어도 돼. label안에 input이 있으면 알아서 연결해줘

2020-07-16 05:21 UTC, mniberyl commented on src/pages/login/index.jsx
> +              </label>
수정했어

2020-07-16 05:46 UTC, choegyumin commented on src/pages/login/index.jsx
> +              </label>
클래스명은 둘 중 하나로 하란 뜻이였어. label, span 각각 쓰지말고 클래스 하나 정해서 BEM으로 해줘

2020-07-16 05:47 UTC, choegyumin requested changes

2020-07-16 05:47 UTC, choegyumin commented on src/styles/pages/_auth.scss
> +    }
`text-decoration: underline;`은 _anchor.scss에 있는데 이것도 거기로 가야하지 않을까?

2020-07-16 06:05 UTC, mniberyl commented on src/pages/login/index.jsx
> +              </label>
수정했어

2020-07-16 06:06 UTC, mniberyl commented on src/styles/pages/_auth.scss
> +    }
수정했어
가상 선택자가 태그 선택자보다 명시도가 높아서 발생한 이슈때문에 
:root를 html로 변경했어

2020-07-16 06:06 UTC, choegyumin commented on src/styles/pages/_auth.scss
> +    }
`:root *:focus` 선택자가 명시도가 높아서 문제가 있었네..
`html *:focus`로 바꾸면 적용될거야

2020-07-16 06:12 UTC, choegyumin commented on src/styles/pages/_auth.scss
> +    }
이러니까 로고도 아웃라인 사라지네....
그냥 a태그의 focus스타일을 underline 빼고 default outline으로 하자..

2020-07-16 06:26 UTC, choegyumin approved these changes

2020-07-16 06:28 UTC, merged