Markup forumlist page
mniberyl/forust pull request #9
Opened 2020-07-26 07:30 UTC by mniberyl

* Add Header component
* Add AppNav, DefaultLayout components
* Add ForumList

2020-07-26 07:38 UTC, choegyumin requested changes

2020-07-26 07:38 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +          </li>
선택된 네비게이션 아이템은 svg 아이콘 컬러를 바꿔야 해. [mask](https://developer.mozilla.org/ko/docs/Web/CSS/mask) 스타일을 쓰면 투명하지 않은 부분만 색상을 바꿀 수 있는데..
그냥 svg를 컴포넌트 처럼 쓸 수 있게 플러그인 추가하자. [여기](https://github.com/vercel/next.js/tree/master/examples/svg-components) 참고해서 적용하고 svg 코드에서 `fill` 값을 `currentColor`로 바꿔서 스타일 입히면 될 것 같아.

2020-07-26 08:49 UTC, choegyumin requested changes

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +          </h1>
`.header-item` 이거 `.app-header` 없이 쓰면 깨지는데,
웬만하면 단독으로 쓸 수 있는 것만 블럭 클래스로 만들고 아님 엘리먼트 클래스로 만들어.
이 코드에서는 이미 `app-header`가 있는데 굳이 `header-*` 같은 블럭 클래스를 만들 필요는 없어 보이네.

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +          </h1>
`.app-logo`는 컴포넌트로 만드는게 좋아 보여

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +          </div>
`<div className="header-item header-container" />` 이걸로 묶지 않아도 디자인대로 그릴 수 있지 않아?

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +              <img src="/images/search.svg" alt="Search" className="header-search__img" />
input type은 `search`로 해줘.
그리고 placeholder는 label 역할을 못해. 지금 label이 없으니까 `aria-label` 추가해서 검색 필드라고 알려줘

input에 label을 추가하면 아이콘 이미지는 스크린 리더에서 읽을 때 더이상 필요없게 돼. 눈으로 봤을 때만 의미가 있지.
alt는 빈 값으로 채우고 `aria-hidden="true"` 해줘

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +            </a>
이거 공지사항 아니고 알림이야. Notification 또는 Inbox가 적절해 보여.

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +            </details>
html5 레퍼런스에 details로 컨트롤 필드를 숨기는 예제도 있어서 시도는 좋았는데..
transition이 안돼서 dropdown 컴포넌트를 직접 만들어야 할 것 같네

아직 드롭다운 디자인도 없으니까 일단 details, summary 태그로 dropdown 컴포넌트 만들고 컴포넌트 안에 todo 달아줘

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +                <img src="/images/chamdori.jpeg" alt="Profile" className="header-profile__img" />
이거 참도리.. 귀여운데 헷갈리니까 파일명은 avatar-sample 이런걸로 하자
그리고 `alt` 의미 없어 보이니까 숨기고, 이미지 없을 때 영역이 제대로 안잡히는데 이것도 고쳐줘.

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +                  <img src="/images/profile-dropdown.svg" alt="Profile-Dropdown" className="header-profile__dropdown-icon" />
로그인 페이지에 로고 마크업할 때랑 마찬가지로 `Profile-Dropdown` 같은 텍스트는 사용자한테 아무 쓸모도 없어
사용자가 읽었을 때 의미가 있는 내용을 넣어야 하고 별 의미 없는 이미지다 싶으면 `alt` 채우기보단 `aria-hidden="true"`로 숨길지 부터 고민해

alt 관련 코멘트는 여기까지만 달게 전부 확인해서 정리해줘

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +          </li>
여기도 AppHeader처럼 불필요한 블럭 클래스 줄여줘

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +        <h2 className="visually-hidden">Your Commutiny</h2>
heading이 적합하지 않네

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +        <ul className="nav-menu" role="listbox" aria-label="nav-heading" aria-activedescendant="help" tabIndex="0">
`aria-label`이 아니라 `aria-labelledby`를 하고싶었던 것 같네.
그리고 `id`가 h2에 안들어가고 nav 엘리먼트에 들어갔어.

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +          </li>
예제를 잘못 찾아서 참고한 것 같아
이건 selectbox 만드는거고 네비게이션에서는 `role`, `aria-activedescendant`, `aria-selected` 이런거 필요없어
현재 페이지와 동일한 링크의 a 태그에 `aria-current="page"`만 있으면 돼

2020-07-26 08:49 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +          <li className="nav-menu__items" role="option" aria-selected="true" id="help">
item이 적절해보여

2020-07-26 08:49 UTC, choegyumin commented on src/styles/pages/_container.scss
> +}
container 페이지는 없지

특벙 페이지에서만 쓰려는거면 2개 이상의 단어 조합으로 클래스명 유니크하게 만들고, 파일명도 바꾸고,
전부 돌려쓰는거면 object 스타일로 만드는게 좋아보여

2020-07-26 08:49 UTC, choegyumin commented on src/layouts/default-layout/default-layout.jsx
> +          {children}
`.app-container`에 `display: flex;`를 넣었고 `children`에 뭐가 들어올지도 모르면
`children`을 엘리먼트로 한번 감싸주는게 좋지 않을까?

2020-07-26 08:49 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +  const [state, dispatch] = useReducer(reducer, { value: 0 });
이거 어차피 목업  코드일테지만 이 코드에서는 굳이 `useReducer`를 쓰기 보단 `useState`를 쓰는게 좋아보여

2020-07-26 08:49 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +            <div className="question-content">
`.question-summary`는 컴포넌트로 만드는게 좋아 보여
Summary 라는 이름은 별로인 것 같고 `QuestionCard`나 아님 이보다 더 적절한걸로 해줘

2020-07-26 08:49 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +              <button type="button" className="recommendation-button recommendation-button__down" aria-label="Down" onClick={() => dispatch({ type: 'DECREMENT' })} />
블럭 클래스와 그 블럭의 엘리먼트 클래스가 같이 있는건 말이 안되지

2020-07-26 08:49 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +              <div className="question-profile">
AppHeader, AppNav처럼 불필요한 블럭 클래스 줄여줘

2020-07-26 08:49 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +                  <a href="forum-list" className="question-user"><img src="/images/chamdori.jpeg" alt="Profile" className="question-user__img" /></a>
이미지 엘리먼트 없을 때 영역이 안잡혀

2020-07-26 08:49 UTC, choegyumin commented on src/styles/elements/_button.scss
> +  }
```scss
*:focus {
  outline: none;
}
```
처음에 _reset.scss에 이렇게 작성했다가 기본 아웃라인 스타일 다 넣기로 했잖아. 빼면 안되지

2020-07-26 08:49 UTC, choegyumin commented on src/styles/elements/_list.scss
> +  }
`.nav-menu`에 `tabIndex="0"`넣어서 생긴걸 여기서 빼면 안되지
ul, ol은 원래 포커스가 안되잖아

2020-07-26 08:53 UTC, choegyumin requested changes
<del></del>

2020-07-26 08:56 UTC, choegyumin requested changes

2020-07-26 08:56 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +export default function ForumList() {
`/` (ForumList)
`/forum/details`
`/forum/write`
`/login`
`/signup`

URL은 이렇게 나오는게 좋아 보여
ForumList는 `/pages/index.jsx`에 작성하지 말고 `pages/forum/list/index.js`에 작성해서 router 설정으로 연결해줘

2020-07-28 03:41 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +              <img src="/images/search.svg" alt="Search" className="header-search__img" />
수정했어

2020-07-28 03:42 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +            </a>
수정했어

2020-07-28 03:43 UTC, mniberyl commented on src/styles/pages/_container.scss
> +}
object 스타일로 만들었어

2020-07-28 04:38 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +export default function ForumList() {
수정했어~

2020-07-28 04:42 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +          </h1>
수정했어~

2020-07-28 04:46 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +            </details>
@todo 달아놨어~

2020-07-28 06:33 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +          </li>
수정했어

2020-07-28 06:34 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +          </h1>
수정했당

2020-07-28 06:34 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +          </div>
수정했어~

2020-07-28 14:51 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +                <img src="/images/chamdori.jpeg" alt="Profile" className="header-profile__img" />
예제 이미지 이름 avatar-sample로 수정했어~
그리고 만약에 사용자 이름이 디자인 예시보다 더 길 경우도 다시 얘기를 해봐야 할 것 같아..

2020-07-28 15:11 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +                <img src="/images/chamdori.jpeg" alt="Profile" className="header-profile__img" />
예제 이미지 이름 avatar-sample로 수정했어~
그리고 사용자 이름이 디자인 예시(Chamdori)보다 더 길 경우에 대해서도 다시 애기해야 할 것 같아~

2020-07-28 15:38 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +                  <img src="/images/profile-dropdown.svg" alt="Profile-Dropdown" className="header-profile__dropdown-icon" />
웅 알겠어

2020-07-29 04:13 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +        <h2 className="visually-hidden">Your Commutiny</h2>
수정했어

2020-07-29 04:13 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +        <ul className="nav-menu" role="listbox" aria-label="nav-heading" aria-activedescendant="help" tabIndex="0">
수정했어

2020-07-29 04:13 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +          </li>
수정했어

2020-07-29 04:22 UTC, mniberyl commented on src/styles/elements/_list.scss
> +  }
수정했어

2020-07-29 04:22 UTC, mniberyl commented on src/styles/elements/_button.scss
> +  }
수정했어

2020-07-29 06:21 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +          </li>
수정했어

2020-07-29 06:23 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +          <li className="nav-menu__items" role="option" aria-selected="true" id="help">
불필요한 블럭 클래스 줄이면서 클래스 이름도 변경했어

2020-07-29 06:57 UTC, mniberyl commented on src/layouts/default-layout/default-layout.jsx
> +          {children}
수정했어

2020-07-29 08:17 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +            <div className="question-content">
컴포넌트로 만들었어~

2020-07-29 14:12 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +              <button type="button" className="recommendation-button recommendation-button__down" aria-label="Down" onClick={() => dispatch({ type: 'DECREMENT' })} />
수정했어

2020-07-30 04:54 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +              <div className="question-profile">
수정했어

2020-07-30 07:13 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +                  <a href="forum-list" className="question-user"><img src="/images/chamdori.jpeg" alt="Profile" className="question-user__img" /></a>
수정했어

2020-07-31 06:00 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +  const [state, dispatch] = useReducer(reducer, { value: 0 });
useState로 썼어

2020-07-31 08:56 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +          </div>
클래스명만 바뀌고 그대로 있네...

2020-07-31 08:57 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +              <img src="/images/search.svg" alt="Search" className="header-search__img" />
img를 svg 태그로 바꿨으면 alt 속성도 빼야지

2020-07-31 08:59 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +            </a>
지난 리뷰 때 놓쳤는데 링크 아니고 버튼이야

2020-07-31 08:59 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +            </details>
dropdown은 한 단어로 쓰면 돼

2020-07-31 09:03 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +            </details>
dropdown은 한 단어로 쓰면 돼

그리고 트랜지션 없이 details, summary 태그를 써서 dropdown을 만들라는거지
그냥 profile 마크업한거 그대로 넣어놓고 냅두라는 뜻은 아니였어

최소한 dropdown 컴포넌트라고 말할 수 있을 정도로는 만들어줘

2020-07-31 09:04 UTC, choegyumin commented on src/components/app-header/app-header.jsx
> +                <img src="/images/chamdori.jpeg" alt="Profile" className="header-profile__img" />
15자까지 보이게 하고 말줄임 하자

2020-07-31 09:07 UTC, choegyumin requested changes

2020-07-31 09:07 UTC, choegyumin commented on src/components/drop-down/drop-down.jsx
> +        <IconCaretDown className="app-user__icon" alt="" aria-hidden="true" />
alt 들어간 svg 전부 찾아서 빼 줘

2020-07-31 09:09 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +        <h2 className="visually-hidden">Your Commutiny</h2>
사람이 귀로 듣는건데 컴포넌트명처럼 `AppNav` 이렇게 하면 안되지
`ForumList`도 마찬가지로 바꿔줘

2020-07-31 09:10 UTC, choegyumin commented on src/components/app-nav/app-nav.jsx
> +        <ul className="nav-menu" role="listbox" aria-label="nav-heading" aria-activedescendant="help" tabIndex="0">
h2의 위치가 잘못됐어
그리고 헤딩의 id인데 `app-nav` 보단 `app-nav-heading`이 낫지 않을까?

2020-07-31 09:14 UTC, choegyumin commented on src/layouts/default-layout/default-layout.jsx
> +          {children}
`.app-index`는 이름만 들었을 때 뭐하는 엘리먼트인지 전혀 감이 안오네..

2020-07-31 09:16 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +  const [state, dispatch] = useReducer(reducer, { value: 0 });
지금 구현해놓은 목업은 실제 스펙이랑 다르니까 주석 없으면 헷갈릴 것 같아
어떻게 작동해야 하는지 todo라도 달아놓자

2020-07-31 09:18 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +            <div className="question-content">
QuestionCard인데 `ul.question-wrapper`로 시작하는거 보니 밖에 있어야 할 엘리먼트를 잘못 넣은거 같네. 이건 뺴줘

그리고 listitem으로만 쓰이는게 아닐 수 있으니까 li 대신 div로 만들고 필요할 때 role 애트리뷰트를 선언하는게 재사용하기 좋아 보여

2020-07-31 09:25 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +              <button type="button" className="recommendation-button recommendation-button__down" aria-label="Down" onClick={() => dispatch({ type: 'DECREMENT' })} />
````html
<button class="button form__submit" />
```

button 블럭과 form 블럭의 submit 엘리먼트 클래스가 합쳐진 케이스야.
이런식으로 블럭 클래스나 엘리먼트 클래스가 여러개 쓰이는건 괜찮지만,

`<button className="question-vote__button question-vote__up" />`

동일한 블럭(question-vote)의 엘리먼트 클래스를 여러개 쓰는건 규칙에 어긋난걸로 알고 있어
up, down은 modifier가 적절해보이네

2020-07-31 09:30 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +                  <a href="forum-list" className="question-user"><img src="/images/chamdori.jpeg" alt="Profile" className="question-user__img" /></a>
이미지가 있을 때는 흰 배경 넣어주고, 없을때는 디자인에 있는 배경색 넣어줘
스타일가이드에 변수로 만들어놨어

그리고 width, height가 32px인데 border-radius는 50px이네
애매한 수치 쓰지말고 32px로 하거나 아님 9999px 같은걸로 해
그래야 가볍게 훑어봤을 때도 코드 파악하기 쉬워

2020-07-31 09:33 UTC, choegyumin commented on src/styles/elements/_button.scss
> +  }
원래 포커스 되어야 하는 요소에 아웃라인 스타일 빼지마
내가 나중에 전체적으로 보면서 대응할게

2020-07-31 09:54 UTC, choegyumin commented on src/pages/forum-list/index.jsx
> +export default function ForumList() {
Home으로 감싸지 말고 ForumList를 바로 리턴해도 될 것 같아

2020-07-31 09:59 UTC, choegyumin requested changes

2020-07-31 09:59 UTC, choegyumin commented on src/components/app-logo/app-logo.jsx
> +      </a>
여기뿐만 아니라 링크 엘리먼트 전부 a 태그 말고 Link 컴포넌트로 바꿔줘
https://nextjs.org/docs/api-reference/next/link

2020-07-31 10:00 UTC, choegyumin requested changes

2020-07-31 10:00 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
> +  }
컬러가 디자인이랑 달라

2020-07-31 10:00 UTC, choegyumin commented on src/components/question-card/question-card.scss
> +}
여백이 디자인이랑 달라

2020-07-31 10:01 UTC, choegyumin commented
클래스명 정리하는거랑 불필요한 엘리먼트 빼는거는 주말에 같이 해보자

2020-08-03 10:23 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +            </a>
수정했어~

2020-08-03 11:02 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +          </div>
이거 무슨 의미인 줄 알았다.. 수정했어!

2020-08-03 14:34 UTC, choegyumin requested changes

2020-08-03 14:34 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
> +  color: $green-dark;
상태 클래스는 단독으로 쓰면 안돼
앞에 다른 클래스랑 조합해서 써야해

2020-08-03 14:34 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
> +  background: rgba(187, 226, 210, 0.25);
scss에서 rgba 함수 쓸 때 rgb는 hex값으로 써도 돼
이거 green-light인데 변수로 대체할 수 있는 건 전부 수정해줘

2020-08-03 15:35 UTC, choegyumin requested changes

2020-08-03 15:35 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +      <div className="question">
충돌을 방지하려면 한단어를 쓰는건 좋지 않아

2020-08-03 15:35 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +      </div>
질문 카드뿐만 아니라 답변 카드에서도 재사용할 것들은 question말고 다른 이름을 써줘

2020-08-03 15:35 UTC, choegyumin commented on src/components/question-card/question-card.jsx
> +    <div className={classNames('question-card card', className)} {...rest}>
card는 오브젝트 스타일로 만들어줘
스타일 가이드 만들어놨어

2020-08-04 04:16 UTC, mniberyl commented on src/components/app-nav/app-nav.scss
> +  color: $green-dark;
수정했어

2020-08-04 04:22 UTC, mniberyl commented on src/components/app-nav/app-nav.scss
> +  background: rgba(187, 226, 210, 0.25);
수정했어

2020-08-04 04:25 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +    <div className={classNames('question-card card', className)} {...rest}>
수정했어

2020-08-04 05:15 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +      </div>
게시글이라는 의미로 question 대신 post로 변경했어

2020-08-04 05:16 UTC, mniberyl commented on src/components/question-card/question-card.jsx
> +      <div className="question">
수정했어~

2020-08-04 05:17 UTC, mniberyl commented on src/components/app-nav/app-nav.scss
> +  }
수정했어

2020-08-04 05:18 UTC, mniberyl commented on src/pages/forum-list/index.jsx
> +  const [state, dispatch] = useReducer(reducer, { value: 0 });
@todo 달아놨어

2020-08-04 05:19 UTC, mniberyl commented on src/layouts/default-layout/default-layout.jsx
> +          {children}
`.app-main` 으로 변경했어

2020-08-04 05:19 UTC, mniberyl commented on src/components/app-header/app-header.jsx
> +                <img src="/images/chamdori.jpeg" alt="Profile" className="header-profile__img" />
수정했어

2020-08-04 09:48 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
> +  background: rgba(187, 226, 210, 0.25);
태그 아이템에 아직 남아있어
그리고 태그 컴포넌트로 만들어줘

2020-08-05 06:32 UTC, mniberyl commented on src/components/drop-down/drop-down.jsx
> +        <IconCaretDown className="app-user__icon" alt="" aria-hidden="true" />
수정했어

2020-08-05 06:32 UTC, mniberyl commented on src/components/app-logo/app-logo.jsx
> +      </a>
수정했어

2020-08-05 07:03 UTC, mniberyl commented on src/components/drop-down/drop-down.jsx
> +        <IconCaretDown className="app-user__icon" alt="" aria-hidden="true" />
수정했어

2020-08-05 07:04 UTC, mniberyl commented on src/components/app-logo/app-logo.jsx
> +      </a>
수정했어

2020-08-05 07:49 UTC, mniberyl commented on src/components/app-nav/app-nav.jsx
> +          </li>
수정했당

2020-08-12 10:18 UTC, choegyumin commented on src/components/app-nav/app-nav.scss
> +  background: rgba(187, 226, 210, 0.25);
색상 전부 hex 값으로 작성하고 있으니까 변수로 관리되지 않는것도 hex로 바꿔줘
`rgba(0, 0, 0, 0.5)` → `rgba(#000, 0.5)`

2020-08-18 10:12 UTC, choegyumin submitted a review, later dismissed

2020-08-18 10:59 UTC, choegyumin approved these changes

2020-08-18 11:01 UTC, merged